services:
  db-auth:
    container_name: db-auth
    image: postgres:latest
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data: